# Generated by Django 6.0 on 2026-01-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cansel_order', 'Can cansel order')]},
        ),
    ]
